config/routes.rb
Medical::Application.routes.draw do
  get "store/index"
  resources :medicines

  root "store#index"

  

end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  validates :title, :description, :image_url, :presence => true
  validates_numericality_of :price, :greater_than_or_equal_to => 10
  validates_uniqueness_of :title
  validates_format_of :image_url, :with => %r{\.(gif|jpg|png)\Z}i , :message => "Must be a url for GIF, JPG, PNG image"
  default_scope :order => 'title'
end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]

  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medicine }
      else
        format.html { render action: 'new' }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @medicines = Medicine.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Medical Store</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "medicine", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="store" >
<div id="banner" >
  <%= image_tag("logo.png") %>
  <%= @page_title || "Medical Store" %>
</div>
<div id="columns" >
  <div id="side" >
    <a href="http://www...." >Home</a><br />
    <a href="http://www..../faq" >Questions</a><br />
    <a href="http://www..../news" >News</a><br />
    <a href="http://www..../contact" >Contact</a><br />
  </div>
  <div id="main" >
    <%= yield %>
  </div>
</div>
</body>
</html>

</html>

app/views/medicines/_form.html.erb
<%= form_for(@medicine) do |f| %>
  <% if @medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

      <ul>
      <% @medicine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicines/edit.html.erb
<h1>Editing medicine</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<div id="medicine_list" >
  <h1>Listing Medicines</h1>
  <table>
    <% @medicines.each do |medicine| %>
        <tr class=" <%= cycle('list_line_odd' , 'list_line_even' ) %>" >
          <td>
            <%= image_tag(medicine.image_url, :class => 'list_image' ) %>
          </td>
          <td class="list_description" >
            <dl>
              <dt><%= medicine.title %></dt>
              <dd><%= truncate(strip_tags(medicine.description),
                               :length => 80) %></dd>
            </dl>
          </td>
          <td class="list_actions" >
            <%= link_to 'Show' , medicine %><br/>
            <%= link_to 'Edit' , edit_medicine_path(medicine) %><br/>
            <%= link_to 'Destroy' , medicine,
                        :confirm => 'Are you sure?' ,
                        :method => :delete %>
          </td>
        </tr>
    <% end %>
  </table>
</div>
<br />
<%= link_to 'New Medicine' , new_medicine_path %>

app/views/medicines/new.html.erb
<h1>New medicine</h1>

<%= render 'form' %>

<%= link_to 'Back', medicines_path %>

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @medicine.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @medicine.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @medicine.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @medicine.price %>
</p>

<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<%= link_to 'Back', medicines_path %>

app/views/store/index.html.erb
<% if notice %>
    <%= notice %>
<% end %>
<h1>Medicines Catalog</h1>
<% @medicines.each do |medicine| %>
    <div class="entry" >
      <%= image_tag(medicine.image_url) %>
      <h3><%= medicine.title %></h3>
      <%=sanitize medicine.description %>
      <div class="price_line" >
        <span class="price" ><%= number_to_currency(medicine.price) %></span>
      </div>
    </div>
<% end %>